/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author Aparna
 */
public class StudentLogIn extends javax.swing.JFrame {
public StudentDataBase c1;
static StudentDataBase logperson;
    /**
     * Creates new form StudentLogIn
     */
    public StudentLogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StudentRollNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        StudentPassword = new javax.swing.JPasswordField();
        SubmitStudentLogIn = new javax.swing.JButton();
        StudentRegister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Student log in");

        jLabel2.setText("Roll no.");

        StudentRollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentRollNoActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        StudentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentPasswordActionPerformed(evt);
            }
        });

        SubmitStudentLogIn.setText("Submit");
        SubmitStudentLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitStudentLogInActionPerformed(evt);
            }
        });

        StudentRegister.setText("Register");
        StudentRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentRegisterActionPerformed(evt);
            }
        });

        jLabel4.setText("Not registered?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(StudentRegister)
                    .addComponent(SubmitStudentLogIn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(StudentRollNo)
                        .addComponent(StudentPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(StudentRollNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(StudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(SubmitStudentLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentRegister)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitStudentLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitStudentLogInActionPerformed
        
        String srn=StudentRollNo.getText();
        String pass=StudentPassword.getText();
        int flag1=0;
        if(srn.equals("")||pass.equals(""))
           
        {
           JOptionPane.showMessageDialog(null, "Empty roll number or password field","Message",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
        try
        {
            FileInputStream fis1 ;
            fis1 = new FileInputStream("students.txt");
            ObjectInputStream ois1 ;
            ois1 = new ObjectInputStream(fis1);
            
            while((c1 = (StudentDataBase)ois1.readObject())!=null)
            {
               // System.out.println(c1.getrollno());
                
                
                if(c1.getrollno().equals(srn) && c1.getpassword().equals(pass))
                {
                    flag1=1;
                    logperson=c1;
                    break;
                }
                          
            }
            ois1.close();
            fis1.close();
        
        }
        catch(EOFException e){}
        catch(ClassNotFoundException ex2){}
        catch(IOException e){}
        catch(NullPointerException np){}
        
        
        
        if(flag1==1)
        {
            String name1=c1.getname();
            JOptionPane.showMessageDialog(null, "You have successfully logged in!\nWelcome "+name1+"!","Message",JOptionPane.INFORMATION_MESSAGE);
            MainPageStudent j=new MainPageStudent();
            this.dispose();
            j.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Invalid name/password ","Message",JOptionPane.INFORMATION_MESSAGE);
            StudentRollNo.setText("");
             StudentPassword.setText("");
        }
      
        
        }
        
    }//GEN-LAST:event_SubmitStudentLogInActionPerformed

    private void StudentRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentRegisterActionPerformed
    StudentReg objstudreg=new StudentReg();
    objstudreg.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_StudentRegisterActionPerformed

    private void StudentRollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentRollNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentRollNoActionPerformed

    private void StudentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField StudentPassword;
    private javax.swing.JButton StudentRegister;
    private javax.swing.JTextField StudentRollNo;
    private javax.swing.JButton SubmitStudentLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
